# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            texasflood
tagline:          Site
url:              https://texasflood.github.com
baseurl:          /
author:
  name:           Anas Syed
  url:            https://texasflood.github.com

comments :
  provider : intensedebate
  intensedebate :
    account : texasflood
