# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
#title:            texasflood
#tagline:          Site
url:              https://texasflood.github.com
baseurl:          /
author:
  name:           Anas Syed
  url:            https://texasflood.github.com

gems: [jekyll-redirect-from]

comments :
  provider : intensedebate
  intensedebate :
    account : texasflood
